[project]
name = "memorymap-chatbot"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "langchain>=0.3.27",
    "notebook>=7.4.5",
    "openai>=1.102.0",
    "streamlit>=1.49.1",
]
